CREATE TABLE [dbo].[BillingDetails]
(
	[Id] INT NOT NULL PRIMARY KEY Identity(1,1),
	[BillingInformationId] int not null,
	[BillingName] nvarchar(max),
	[CustomerStr] nvarchar(max),
	[SalesAgentId] int,
	[IsPaperBillRequired] bit,
	[BirthDate] Datetime,
	[InstallationDate] Datetime,
	[CPEType] nvarchar(max),
	[VerificationStatus] nvarchar(max),
	[IsInitialPaymentReceived] bit,
	[BillReceivedByCrStatus] nvarchar(max),
	[VerificationRemarks] nvarchar(max),
	[InstalledBy] nvarchar(max),
	[MGM_ExistingCustomerSng] nvarchar(max),
	[InfinityMigrationCategory] nvarchar(max),
	[InfinityRefMLR] nvarchar(max),
	[CollectionAgent] nvarchar(max),
	[NationalIdNo] nvarchar(max),
	[PassportNo] nvarchar(max),
	[RetailOutletID] int,
	[AgeRange] nvarchar(max),
	[InfinityRefAccNo] nvarchar(max),
	[InfinityMappedQubeePackageId] int,
	[BillDeliveryCrStatusDate] Datetime,
	[RefName1] nvarchar(max),
	[RefContact1]  nvarchar(max),
	[RefEmail1]  nvarchar(max),
	[RefCNIC1] nvarchar(max),
	[RefAddress1] nvarchar(max),
	[RefName2] nvarchar(max),
	[RefContact2]  nvarchar(max),
	[RefEmail2]  nvarchar(max),
	[RefCNIC2] nvarchar(max),
	[RefAddress2] nvarchar(max),
	[CSAFNumber] nvarchar(max),
	[Reason] nvarchar(max),
	[InfinityRefCPEType] nvarchar(max),
	[CustomerNTN] nvarchar(max),
	[WifiRouter] nvarchar(max),
	[Package] nvarchar(max),
	[InfinityUnsuccessfulMigrationReason] nvarchar(max),
	[SalesRepId] int,
	[BillingStatus] int default(0),
	[IsDirectBilling] bit not null default(0),
	[CreatedBy] nvarchar(max),
	[CreatedAt] DateTime,
	[UpdatedBy] nvarchar(max),
	[UpdatedAt] DateTime,
	[Date] Datetime,
	Constraint [FK_BillingDetails_BillingInfromation] foreign key ([BillingInformationId]) References [dbo].[BillingInformation] ([Id]),
)
