CREATE TABLE [dbo].[Company]
(
	[Id] INT NOT NULL PRIMARY KEY Identity(1,1),
	[BillingInformationId] int null,
	[IsDirectBilling] bit,
	[AgentId] INT,
	[Name] nvarchar (max) ,
	[IsBranch] bit,
	[IsParent] bit,
	[ParentCompanyId] int,
	[Latitude] float,
	[Longitude] float,
	[Address] nvarchar(max),
	[Contact]  nvarchar (max) ,
	[Email]  nvarchar (max) ,
	[Description] nvarchar(max),
	[ModeOfCommunication] int,
	[BusinessOperationTime] int,
	[AlternateNumber] nvarchar(max),
	[Website] nvarchar(max),
	[Area] int,
	[City] int,
	[NoEmployee] int,
	[BusinessIndustry] int,
	[CurrentItPlatform] nvarchar(max),
	[CUDS]int,
	[CUDSService] int,
	[CUDSOtherService] nvarchar(max),
	[NoLinks] int,
	[NTN] nvarchar(max),
	[NumberOfBranchOffices] int,
	[CreatedAt] Datetime ,
	[UpdatedAt] Datetime ,
	[CreatedBy] nvarchar(max),
	[UpdatedBy] nvarchar(max),
	[Date] Datetime,
    Constraint [FK_Company_ParentCompany] foreign key ([ParentCompanyId]) References [dbo].[Company] ([Id]),
	Constraint [FK_Company_Agent] foreign key ([AgentId]) References [dbo].[Agent] ([Id]),

)
