CREATE TABLE [dbo].[Invoice]
(
	[Id] INT NOT NULL PRIMARY KEY Identity(1,1),
	[Type] int default(0),
	[IsPosted] bit not null,
	[Status] int not null,
	[CompanyId] int not null,
	[StartDate] Datetime,
	[EndDate] Datetime,
	[AccountId] int,
	[InvoiceCode] nvarchar(max),
	[AttendantName] nvarchar(max),
	[CompanyAddress] nvarchar(max),
	[CompanyContact] nvarchar(max),
	[MonthlyCharges] decimal(18,3) default(0),
	[NTN] nvarchar(max),
	[CompanyEmail] nvarchar(max),
	[LinkName] Nvarchar(max),
	[PackageId] nvarchar(max),
	[GorssAmount] decimal(18,3)default(0),
	[AmountType] int,
	[TotalAmount] decimal(18,3)default(0),
	[TaxWitholdingAmount] decimal(18,3)default(0),
	[AgentId] int,
	[CreatedBy] nvarchar(max),
	[CreatedAt] DateTime,
	[UpdatedBy] nvarchar(max),
	[UpdatedAt] DateTime,
	[Date] Datetime,
	[DueDate] Datetime,
	Constraint [FK_Invoice_Company] foreign key ([CompanyId]) References [dbo].[Company] ([Id]),
	Constraint [FK_Invoice_Agent] foreign key ([AgentId]) References [dbo].[Agent] ([Id]),
	Constraint [FK_Invoice_Account] foreign key ([AccountId]) References [dbo].[Account] ([Id]),
)
