CREATE TABLE [dbo].[PurchaseOrder]
(
	[Id] INT NOT NULL PRIMARY KEY Identity(1,1),
	[Status] int not null default(0),
	[LeadId] int,
	[CompanyId] int, 
	[BillingStatus] int not null default(0),
	[AssignedDepartmentId] int,
	[AssignedCoreAgentId] int,
	[AssignedSDAgentId] int,
	[AssignedPresalesAgentId] int,
	[OTC] decimal(18,3) not null default(0),
	[MRC] decimal(18,3) not null default(0),
	[Package] nvarchar(max),
	[Description] nvarchar(max),
	[CreatedAt] Datetime ,
	[UpdatedAt] Datetime ,
	[CreatedBy] nvarchar(max),
	[UpdatedBy] nvarchar(max),
	[Date] Datetime,
	[CoreProcessStatus] int,
	[PresalesProcessStatus] int,
	[SdProcessStatus] int,
	[VendorProcessStatus] int,
	[PresalesApproval] int,
	[SDSuggestedVendorId1] int,
	[SDSuggestedVendorId2] int,
	[SDSuggestedVendorId3] int,
	[CoreIp] nvarchar(max),
	[CoreVlanId ] nvarchar(max),
	[SDClientVerification] bit,
	Constraint [FK_PO_CoreAgent] foreign key ([AssignedCoreAgentId]) References [dbo].[Agent] ([Id]),
	Constraint [FK_PO_SDAgent] foreign key ([AssignedSDAgentId]) References [dbo].[Agent] ([Id]),
	Constraint [FK_PO_PresaleAgent] foreign key ([AssignedPresalesAgentId]) References [dbo].[Agent] ([Id]),
	Constraint [FK_PO_Company] foreign key ([CompanyId]) References [dbo].[Company] ([Id]),
	Constraint [FK_PO_Lead] foreign key ([LeadId]) References [dbo].[Lead] ([Id]),
)
