//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sharptel_Lms_DbEntities : DbContext
    {
        public Sharptel_Lms_DbEntities()
            : base("name=Sharptel_Lms_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<CompanyBranches> CompanyBranches { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<PmdDetails> PmdDetails { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Lead> Lead { get; set; }
        public virtual DbSet<SolutionDetails> SolutionDetails { get; set; }
        public virtual DbSet<QuestionnareDetails> QuestionnareDetails { get; set; }
        public virtual DbSet<BugReporting> BugReporting { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountEntries> AccountEntries { get; set; }
        public virtual DbSet<BillingDetails> BillingDetails { get; set; }
        public virtual DbSet<BillingInformation> BillingInformation { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Charge> Charge { get; set; }
        public virtual DbSet<ChargeDetails> ChargeDetails { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceDetails> InvoiceDetails { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual DbSet<AgentAttendance> AgentAttendance { get; set; }
        public virtual DbSet<CompanySubcription> CompanySubcription { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TicketComments> TicketComments { get; set; }
    }
}
