//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public int CompanyId { get; set; }
        public int PaymentType { get; set; }
        public string CheckNumber { get; set; }
        public int Status { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string BankName { get; set; }
        public string DepositedBank { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Company Company { get; set; }
    }
}
