//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmdDetails
    {
        public int Id { get; set; }
        public Nullable<int> LeadId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<decimal> OTC { get; set; }
        public Nullable<decimal> MRC { get; set; }
        public string Bandwidth { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int ConnectivityType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
