//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int Id { get; set; }
        public int Status { get; set; }
        public Nullable<int> LeadId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int BillingStatus { get; set; }
        public Nullable<int> AssignedDepartmentId { get; set; }
        public Nullable<int> AssignedCoreAgentId { get; set; }
        public Nullable<int> AssignedSDAgentId { get; set; }
        public Nullable<int> AssignedPresalesAgentId { get; set; }
        public decimal OTC { get; set; }
        public decimal MRC { get; set; }
        public string Package { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CoreProcessStatus { get; set; }
        public Nullable<int> PresalesProcessStatus { get; set; }
        public Nullable<int> SdProcessStatus { get; set; }
        public Nullable<int> VendorProcessStatus { get; set; }
        public Nullable<int> PresalesApproval { get; set; }
        public Nullable<int> SDSuggestedVendorId1 { get; set; }
        public Nullable<int> SDSuggestedVendorId2 { get; set; }
        public Nullable<int> SDSuggestedVendorId3 { get; set; }
        public string CoreIp { get; set; }
        public string CoreVlanId_ { get; set; }
        public Nullable<bool> SDClientVerification { get; set; }
    
        public virtual Agent CoreAgent { get; set; }
        public virtual Agent PresalesAgent { get; set; }
        public virtual Agent SDAgent { get; set; }
        public virtual Company Company { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
