//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnareDetails
    {
        public int Id { get; set; }
        public int LeadId { get; set; }
        public string Requirements { get; set; }
        public string HeadOffice { get; set; }
        public string BranchOffice { get; set; }
        public string Details { get; set; }
        public int Type { get; set; }
    
        public virtual Lead Lead { get; set; }
    }
}
