//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolutionDetails
    {
        public int Id { get; set; }
        public int LeadId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int SolutionType { get; set; }
        public Nullable<int> SolutionSubType { get; set; }
        public string SolutionServiceProvider { get; set; }
        public string SolutionServiceProduct { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string CurrentServiceInfo { get; set; }
        public Nullable<int> Duration { get; set; }
        public string OtherMeasurements { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Lead Lead { get; set; }
    }
}
