//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketComments = new HashSet<TicketComments>();
        }
    
        public int Id { get; set; }
        public int AgentId { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> AssignedToId { get; set; }
        public Nullable<int> AssignedDepartmentId { get; set; }
        public int Status { get; set; }
        public string Name { get; set; }
        public string Media { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Region { get; set; }
        public string ComplaintMedia { get; set; }
        public string Remarks { get; set; }
        public string VisitCall { get; set; }
        public Nullable<System.DateTime> EscalationDateTime { get; set; }
        public Nullable<System.DateTime> RestorationDateTime { get; set; }
        public Nullable<int> ShiftEngineerAgentId { get; set; }
        public string RFO { get; set; }
        public string OwnerShip { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Problem { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual Agent AssignedAgent { get; set; }
        public virtual Agent ShiftEngineerAgent { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketComments> TicketComments { get; set; }
    }
}
